### ISSUE TITLE
Go to definition using CMD+Click

### ISSUE THREAD

**Issue by muhammad-saleh** [rexebin/F12-Open-File#1]
Hi,
Thanks a lot for this extension, so far it works really well

In VSCode when you click on anything (a function name for example) while pressing CMD it will take you to it's definition

If this extension could work the same way it would be great

So along with F12 or right click and selecting go to definition it would be great if I could press CMD and click the style/template path and it takes me there

the current behavior is that if I pressed CMD it will open the style/template file on hover and not on click

**Comment by rexebin** [comment]
Thanks, it will indeed open on hover. I will look into it.

**Comment by rexebin** [comment]
@muhammad-saleh I can change the CMD hover behavior, but by doing this, we will lost the ability to open definition side by side.

What is your opinion? the ability to open side by side or normal go to definition behavior?

Not to worry, I will change to the normal definition provider. 

Just found out that CMD+ALT would open definition side by side.

**Comment by muhammad-saleh** [comment]
@rexebin to be honest I prefer the VSCode/Webstorm default behavior to just CMD+Click to go to definition
I guess it will also be nice because people will expect this behavior

**Comment by rexebin** [comment]
@muhammad-saleh Update  is coming.

CMD+ALT + Click to open side by side.

**Comment by muhammad-saleh** [comment]
Awesome! Thanks a lot again :)

**Comment by rexebin** [comment]
Thanks for the report.

**Comment by rexebin** [comment]
@muhammad-saleh updated.

Have you tried the other extension by me: ClassLens?

Closing the issue.

**Comment by muhammad-saleh** [comment]
I didn't till now!
Looks nice too, I would be excited for any extension that ports a missing feature from Webstorm to VSCode :D

**Comment by rexebin** [comment]
ClassLens is one that I miss the most.

Vscode's codelens provider rely on codelens, so Classlens has to wait until all codelens is completed. 

I have optimized Classlens so that it would not cost any unnecessary resource. It is safe to use.

**Comment by muhammad-saleh** [comment]
Perfect, Will check it out 👍
