### ISSUE TITLE
Go to definition not working with error Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by krist-jin** [rexebin/F12-Open-File#3]
VS code Version: 1.41.0
Commit: 9579eda
Date: 2019-12-11T17:58:38.338Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

Steps to Reproduce:

1. in a ts file right click on a variable name and select go to definition (or cmd+click on that variable)
2. an error is shown: Cannot read property 'toString' of undefined
error from developer console:
notificationsAlerts.ts:38 TypeError: Cannot read property 'toString' of undefined
at _compareReferences (referencesModel.ts:297)
at Array.sort ()
at new u (referencesModel.ts:166)
at W._getLocationModel (goToCommands.ts:204)
at processTicksAndRejections (internal/process/task_queues.js:89)

First I thought it's a vscode bug but after I disable this extension the issue does not occur.

**Comment by leye0** [comment]
I confirm that whenever I install this extension in any Mac or Windows recent VSCode, the "Go to definition" is borked with the mentioned message above. Has been there for almost a month.

**Comment by rexebin** [comment]
Thank you for reporting. I will have a look after new year.

**Comment by rexebin** [comment]
Fixed with 0.3.2.
